#!/bin/bash
#
# Automatically adds branch name and branch description to every commit message.
# Modified from the gist here https://gist.github.com/bartoszmajsak/1396344
#

# This way you can customize which branches should be skipped when
# prepending commit message.
BRANCHES_TO_SKIP=("master" "production" "staging" "main" "develop")

AUTHOR_INFO=$(git var GIT_AUTHOR_IDENT) || exit 1
NAME=$(printf '%s\n\n' "${AUTHOR_INFO}" | sed -n 's/^\(.*\) <.*$/\1/p')

# Get branch name
BRANCH_NAME=$(git symbolic-ref --short HEAD)

# Branch name should be excluded from the prepend
if [ -n "$BRANCH_NAME" ] && ! [[ "${BRANCHES_TO_SKIP[*]}" =~ (^| )$BRANCH_NAME($| ) ]] && ! grep -q "$BRANCH_NAME" "$1"; then
  sed -i.bak -e "1s/^/[$BRANCH_NAME] /" "$1"
fi
