version: '3'

services:
  docker-mysql-db:
    container_name: docker-mysql-db
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - './docker/my_data:/var/lib/mysql'
      - './docker/my.cnf:/etc/mysql/conf.d/my.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: hello123
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
